### PR TITLE
Remove check for package json

### PR DESCRIPTION
**Pull request by CompuIves**
Stumbled upon this strange issue here: https://codesandbox.io/s/qn1wVoor

Where the main of `react-portal` was not recognized. It now works if I remove this first check and change the other check.

I believe the other check is a small mistake, this will always return true if one of both doesn't exist. I believe it should return true if both does not exist.

I'm not sure what the first check is for, do you remember @christianalfoni?

### CODE REVIEW

**Comment by christianalfoni** [comment]
Ah, yeah... actually this part of the codebase is to extract package.json files that are used for redirects... man, I should start commenting :-)

So the line you removed makes sure that no `package.json` related to the NPM package itself is used as "redirect logic".

Looking into react-portal now...

**Comment by christianalfoni** [comment]
Hm, `react-portal` works fine in Webpackbin... there is nothing special about that project as I see it? Hm hm hm... sure there is nothing else going on here? :)

**Comment by CompuIves** [comment]
Bwah that's strange, I'll double check this evening.

**Comment by CompuIves** [comment]
That's strange, I still see the original error.

I see that the externals of the [manifest](https://cdn.jsdelivr.net/webpack/v3/react%4015.5.3+react-dom%4015.5.3+react-portal%403.1.0/manifest.json) don't contain `react-portal`:

screen shot 2017-05-24 at 00 02 51

**Comment by CompuIves** [comment]
Reproduced in WebpackBin: https://www.webpackbin.com/bins/-KkrKd53emU0LuCADd8M.

**Pull request closed without merging**
